In [123]:
import pandas as pd 
base = pd.read_csv('house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [124]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [125]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [126]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [127]:
base = pd.read_csv('house-prices.csv', usecols = colunas_usadas)

In [128]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [129]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [130]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [131]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [132]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [133]:
X = base.drop('price', axis = 1)
y = base.price 

In [134]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [135]:
type(X)

pandas.core.frame.DataFrame

In [136]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [137]:
type(y)

pandas.core.series.Series

In [138]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [139]:
import tensorflow as tf

In [140]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [141]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [142]:
X_treinamento.shape

(15129, 16)

In [143]:
y_treinamento.shape

(15129,)

In [144]:
X_teste.shape

(6484, 16)

In [145]:
funcao_treinamento = tf.compat.v1.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento, batch_size = 32, num_epochs = None, shuffle = True)

In [146]:
funcao_teste = tf.compat.v1.estimator.inputs.pandas_input_fn(x = X_teste, y = y_teste, batch_size = 32, num_epochs = 10000, shuffle = False)

In [147]:
regressor = tf.compat.v1.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\isac_\\AppData\\Local\\Temp\\tmpusxrrnvj', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001FFF2A61E48>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [148]:
regressor.train(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\isac_\AppData\Local\Temp\tmpusxrrnvj\model.ckpt.
INFO:tensorflow:loss = 0.13982032, step = 0
INFO:tensorflow:global_step/sec: 193.941
INFO:tensorflow:loss = 0.10056938, step = 100 (0.520 sec)
INFO:tensorflow:global_s

INFO:tensorflow:global_step/sec: 372.743
INFO:tensorflow:loss = 0.04048694, step = 7200 (0.268 sec)
INFO:tensorflow:global_step/sec: 371.36
INFO:tensorflow:loss = 0.01519517, step = 7300 (0.269 sec)
INFO:tensorflow:global_step/sec: 364.609
INFO:tensorflow:loss = 0.010137466, step = 7400 (0.272 sec)
INFO:tensorflow:global_step/sec: 364.609
INFO:tensorflow:loss = 0.019510403, step = 7500 (0.275 sec)
INFO:tensorflow:global_step/sec: 384.163
INFO:tensorflow:loss = 0.025977004, step = 7600 (0.263 sec)
INFO:tensorflow:global_step/sec: 391.674
INFO:tensorflow:loss = 0.026373336, step = 7700 (0.254 sec)
INFO:tensorflow:global_step/sec: 375.534
INFO:tensorflow:loss = 0.014484284, step = 7800 (0.265 sec)
INFO:tensorflow:global_step/sec: 359.38
INFO:tensorflow:loss = 0.0340778, step = 7900 (0.277 sec)
INFO:tensorflow:global_step/sec: 361.977
INFO:tensorflow:loss = 0.010879025, step = 8000 (0.275 sec)
INFO:tensorflow:global_step/sec: 384.167
INFO:tensorflow:loss = 0.04731507, step = 8100 (0.264 se

In [149]:
metricas_treinamento = regressor.evaluate(input_fn = funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-01-15T15:38:39Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\isac_\AppData\Local\Temp\tmpusxrrnvj\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [40

In [150]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-01-15T15:39:05Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\isac_\AppData\Local\Temp\tmpusxrrnvj\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [40

In [151]:
metricas_treinamento

{'average_loss': 0.0006605197,
 'label/mean': 0.06071797,
 'loss': 0.02113663,
 'prediction/mean': 0.058563646,
 'global_step': 10000}

In [152]:
metricas_teste

{'average_loss': 0.0008115162,
 'label/mean': 0.06163019,
 'loss': 0.025968518,
 'prediction/mean': 0.059484437,
 'global_step': 10000}

In [153]:
funcao_previsao =  tf.compat.v1.estimator.inputs.pandas_input_fn(x = X_teste, shuffle = False)

In [154]:
previsoes = regressor.predict(input_fn = funcao_previsao)

In [155]:
list(previsoes)

INFO:tensorflow:Calling model_fn.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\isac_\AppData\Local\Temp\tmpusxrrnvj\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.05193644], dtype=float32)},
 {'predictions': array([0.04789631], dtype=float32)},
 {'predictions': array([0.12897426], dtype=float32)},
 {'predictions': array([0.04874482], dtype=float32)},
 {'predictions': array([0.12155537], dtype=float32)},
 {'predictions': array([0.09318819], dtype=float32)},
 {'predictions': array([0.05421142], dtype=float32)},
 {'predictions': array([0.07935759], dtype=float32)},
 {'predictions': array([0.05076586], dtype=float32)},
 {'predictions': array([0.15200487], dtype=float32)},
 {'predictions': array([0.02712471], dtype=float32)},
 {'predictions': array([0.06331854], dtype=float32)},
 {'predictions': array([0.06348927], dtype=float32)},
 {'predictions': array([0.12197431], dtype=float32)},
 {'predictions': array([0.05264761], dtype=float32)},
 {'predictions': array([0.11045299], dtype=float32)},
 {'predictions': array([0.04156503], dtype=float32)},
 {'predictions': array([0.08801126], dtype=float32)},
 {'predictions': array([0.07

In [156]:
valores_previsoes = []
for p in regressor.predict(input_fn = funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\isac_\AppData\Local\Temp\tmpusxrrnvj\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [157]:
valores_previsoes

[array([0.05193644], dtype=float32),
 array([0.04789631], dtype=float32),
 array([0.12897426], dtype=float32),
 array([0.04874482], dtype=float32),
 array([0.12155537], dtype=float32),
 array([0.09318819], dtype=float32),
 array([0.05421142], dtype=float32),
 array([0.07935759], dtype=float32),
 array([0.05076586], dtype=float32),
 array([0.15200487], dtype=float32),
 array([0.02712471], dtype=float32),
 array([0.06331854], dtype=float32),
 array([0.06348927], dtype=float32),
 array([0.12197431], dtype=float32),
 array([0.05264761], dtype=float32),
 array([0.11045299], dtype=float32),
 array([0.04156503], dtype=float32),
 array([0.08801126], dtype=float32),
 array([0.07653325], dtype=float32),
 array([0.06079008], dtype=float32),
 array([0.02130444], dtype=float32),
 array([0.0714291], dtype=float32),
 array([0.06772306], dtype=float32),
 array([0.1192693], dtype=float32),
 array([0.02421343], dtype=float32),
 array([0.00030454], dtype=float32),
 array([0.05731034], dtype=float32),
 ar

In [158]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1, 1)

In [159]:
valores_previsoes

array([[ 0.05193644],
       [ 0.04789631],
       [ 0.12897426],
       ...,
       [-0.0011067 ],
       [ 0.05889229],
       [ 0.10974217]], dtype=float32)

In [160]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[ 471015.38],
       [ 440209.38],
       [1058428.8 ],
       ...,
       [  66561.4 ],
       [ 524053.66],
       [ 911784.06]], dtype=float32)

In [161]:
y_teste

2715     0.032984
8064     0.044852
19091    0.087869
18269    0.045902
19837    0.154856
           ...   
18615    0.053508
15316    0.054820
13295    0.011410
7285     0.052452
3282     0.121705
Name: price, Length: 6484, dtype: float64

In [162]:
y_teste.shape

(6484,)

In [163]:
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(6484, 1)

In [164]:
y_teste2 = scaler_y.inverse_transform(y_teste2)
y_teste2

array([[ 326500.],
       [ 417000.],
       [ 745000.],
       ...,
       [ 162000.],
       [ 474950.],
       [1003000.]])

In [165]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [167]:
mae

125047.3133545063